/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedDashboardBookmarksRouteImport } from './routes/_authed/dashboard/bookmarks'
import { Route as AuthedDashboardExploreRouteImport } from './routes/_authed/dashboard/explore'
import { Route as AuthedDashboardFeedRouteImport } from './routes/_authed/dashboard/feed'
import { Route as AuthedDashboardTrendingRouteImport } from './routes/_authed/dashboard/trending'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardBookmarksRoute =
  AuthedDashboardBookmarksRouteImport.update({
    id: '/dashboard/bookmarks',
    path: '/dashboard/bookmarks',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardExploreRoute = AuthedDashboardExploreRouteImport.update({
  id: '/dashboard/explore',
  path: '/dashboard/explore',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardFeedRoute = AuthedDashboardFeedRouteImport.update({
  id: '/dashboard/feed',
  path: '/dashboard/feed',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardTrendingRoute = AuthedDashboardTrendingRouteImport.update({
  id: '/dashboard/trending',
  path: '/dashboard/trending',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/dashboard/bookmarks': typeof AuthedDashboardBookmarksRoute
  '/dashboard/explore': typeof AuthedDashboardExploreRoute
  '/dashboard/feed': typeof AuthedDashboardFeedRoute
  '/dashboard/trending': typeof AuthedDashboardTrendingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/dashboard/bookmarks': typeof AuthedDashboardBookmarksRoute
  '/dashboard/explore': typeof AuthedDashboardExploreRoute
  '/dashboard/feed': typeof AuthedDashboardFeedRoute
  '/dashboard/trending': typeof AuthedDashboardTrendingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/dashboard/bookmarks': typeof AuthedDashboardBookmarksRoute
  '/_authed/dashboard/explore': typeof AuthedDashboardExploreRoute
  '/_authed/dashboard/feed': typeof AuthedDashboardFeedRoute
  '/_authed/dashboard/trending': typeof AuthedDashboardTrendingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/signup'
    | '/sso-callback'
    | '/onboarding'
    | '/dashboard/bookmarks'
    | '/dashboard/explore'
    | '/dashboard/feed'
    | '/dashboard/trending'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/signup'
    | '/sso-callback'
    | '/onboarding'
    | '/dashboard/bookmarks'
    | '/dashboard/explore'
    | '/dashboard/feed'
    | '/dashboard/trending'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/sso-callback'
    | '/_authed/onboarding'
    | '/_authed/dashboard/bookmarks'
    | '/_authed/dashboard/explore'
    | '/_authed/dashboard/feed'
    | '/_authed/dashboard/trending'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/bookmarks': {
      id: '/_authed/dashboard/bookmarks'
      path: '/dashboard/bookmarks'
      fullPath: '/dashboard/bookmarks'
      preLoaderRoute: typeof AuthedDashboardBookmarksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/explore': {
      id: '/_authed/dashboard/explore'
      path: '/dashboard/explore'
      fullPath: '/dashboard/explore'
      preLoaderRoute: typeof AuthedDashboardExploreRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/feed': {
      id: '/_authed/dashboard/feed'
      path: '/dashboard/feed'
      fullPath: '/dashboard/feed'
      preLoaderRoute: typeof AuthedDashboardFeedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/trending': {
      id: '/_authed/dashboard/trending'
      path: '/dashboard/trending'
      fullPath: '/dashboard/trending'
      preLoaderRoute: typeof AuthedDashboardTrendingRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedDashboardBookmarksRoute: typeof AuthedDashboardBookmarksRoute
  AuthedDashboardExploreRoute: typeof AuthedDashboardExploreRoute
  AuthedDashboardFeedRoute: typeof AuthedDashboardFeedRoute
  AuthedDashboardTrendingRoute: typeof AuthedDashboardTrendingRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedDashboardBookmarksRoute: AuthedDashboardBookmarksRoute,
  AuthedDashboardExploreRoute: AuthedDashboardExploreRoute,
  AuthedDashboardFeedRoute: AuthedDashboardFeedRoute,
  AuthedDashboardTrendingRoute: AuthedDashboardTrendingRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SsoCallbackRoute: SsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
