/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSsoCallbackRouteImport } from './routes/_auth/sso-callback'
import { Route as AuthedAppRouteImport } from './routes/_authed/_app'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedAppBookmarksRouteImport } from './routes/_authed/_app/bookmarks'
import { Route as AuthedAppExploreRouteImport } from './routes/_authed/_app/explore'
import { Route as AuthedAppProfileRouteImport } from './routes/_authed/_app/profile'
import { Route as AuthedAppSettingsRouteImport } from './routes/_authed/_app/settings'
import { Route as AuthedAppTrendingRouteImport } from './routes/_authed/_app/trending'
import { Route as AuthedAppFeedRouteImport } from './routes/_authed/_app/feed.'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSsoCallbackRoute = AuthSsoCallbackRouteImport.update({
  id: '/_auth/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppBookmarksRoute = AuthedAppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppExploreRoute = AuthedAppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppProfileRoute = AuthedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSettingsRoute = AuthedAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppTrendingRoute = AuthedAppTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppFeedRoute = AuthedAppFeedRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => AuthedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/sso-callback': typeof AuthSsoCallbackRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/bookmarks': typeof AuthedAppBookmarksRoute
  '/explore': typeof AuthedAppExploreRoute
  '/profile': typeof AuthedAppProfileRoute
  '/settings': typeof AuthedAppSettingsRoute
  '/trending': typeof AuthedAppTrendingRoute
  '/feed/': typeof AuthedAppFeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/sso-callback': typeof AuthSsoCallbackRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/bookmarks': typeof AuthedAppBookmarksRoute
  '/explore': typeof AuthedAppExploreRoute
  '/profile': typeof AuthedAppProfileRoute
  '/settings': typeof AuthedAppSettingsRoute
  '/trending': typeof AuthedAppTrendingRoute
  '/feed': typeof AuthedAppFeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/sso-callback': typeof AuthSsoCallbackRoute
  '/_authed/_app': typeof AuthedAppRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/_app/bookmarks': typeof AuthedAppBookmarksRoute
  '/_authed/_app/explore': typeof AuthedAppExploreRoute
  '/_authed/_app/profile': typeof AuthedAppProfileRoute
  '/_authed/_app/settings': typeof AuthedAppSettingsRoute
  '/_authed/_app/trending': typeof AuthedAppTrendingRoute
  '/_authed/_app/feed/': typeof AuthedAppFeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/signup'
    | '/sso-callback'
    | '/onboarding'
    | '/bookmarks'
    | '/explore'
    | '/profile'
    | '/settings'
    | '/trending'
    | '/feed/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/signup'
    | '/sso-callback'
    | '/onboarding'
    | '/bookmarks'
    | '/explore'
    | '/profile'
    | '/settings'
    | '/trending'
    | '/feed'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authed'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_auth/sso-callback'
    | '/_authed/_app'
    | '/_authed/onboarding'
    | '/_authed/_app/bookmarks'
    | '/_authed/_app/explore'
    | '/_authed/_app/profile'
    | '/_authed/_app/settings'
    | '/_authed/_app/trending'
    | '/_authed/_app/feed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthSsoCallbackRoute: typeof AuthSsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sso-callback': {
      id: '/_auth/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof AuthSsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_app/bookmarks': {
      id: '/_authed/_app/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthedAppBookmarksRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/explore': {
      id: '/_authed/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthedAppExploreRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/profile': {
      id: '/_authed/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedAppProfileRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/settings': {
      id: '/_authed/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedAppSettingsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/trending': {
      id: '/_authed/_app/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof AuthedAppTrendingRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/feed/': {
      id: '/_authed/_app/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof AuthedAppFeedRouteImport
      parentRoute: typeof AuthedAppRoute
    }
  }
}

interface AuthedAppRouteChildren {
  AuthedAppBookmarksRoute: typeof AuthedAppBookmarksRoute
  AuthedAppExploreRoute: typeof AuthedAppExploreRoute
  AuthedAppProfileRoute: typeof AuthedAppProfileRoute
  AuthedAppSettingsRoute: typeof AuthedAppSettingsRoute
  AuthedAppTrendingRoute: typeof AuthedAppTrendingRoute
  AuthedAppFeedRoute: typeof AuthedAppFeedRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppBookmarksRoute: AuthedAppBookmarksRoute,
  AuthedAppExploreRoute: AuthedAppExploreRoute,
  AuthedAppProfileRoute: AuthedAppProfileRoute,
  AuthedAppSettingsRoute: AuthedAppSettingsRoute,
  AuthedAppTrendingRoute: AuthedAppTrendingRoute,
  AuthedAppFeedRoute: AuthedAppFeedRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthSsoCallbackRoute: AuthSsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
